CREATE TABLE IF NOT EXISTS POSITION (
  id   INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPLOYEE (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  position_id INT          NOT NULL,
  name        VARCHAR(255) NOT NULL,
  surname     VARCHAR(255) NOT NULL,
  hire_date   DATE         NOT NULL,
  salary      DOUBLE       NOT NULL,
  FOREIGN KEY (position_id) REFERENCES POSITION (id)
);